# deploy.yml

name: Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
        run: |
          # 여기에 EC2 서버에서 실행할 배포 명령어를 작성합니다.
          # 예시: SSH로 접속하여 프로젝트를 git pull하고, 애플리케이션을 재시작합니다.
          ssh -o StrictHostKeyChecking=no ${EC2_USERNAME}@${EC2_PUBLIC_IP} << 'EOF'
            cd /home/ubuntu/your-project-directory  # 프로젝트 디렉토리로 이동
            git pull origin main                     # 최신 코드 받아오기
            
            # 필요한 경우 의존성 설치 (예: Node.js 프로젝트)
            # npm install
            
            # 애플리케이션 재시작 (예: pm2 사용)
            # pm2 restart your-app-name
            
            echo "Deployment completed successfully!"
          EOF
